# Generated by Django 2.2.7 on 2019-11-07 07:05

from django.db import migrations, models
import quickstart.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paradigm', models.CharField(max_length=50)),
                ('fingerprint', models.ImageField(blank=True, null=True, upload_to=quickstart.models.get_image_path)),
            ],
        ),
    ]
